const { Cpm, Activity } = require("./cpm.js");

const testActivities1 = [
  new Activity("B", 3),
  new Activity("D", 4, ["A", "B"]),
  new Activity("C", 3, ["A", "B"]),
  new Activity("H", 5, ["F", "G"]),
  new Activity("E", 3, ["C"]),
  new Activity("F", 6, ["C"]),
  new Activity("A", 3),
  new Activity("G", 2, ["D", "E"]),
];

const testActivities2 = [
  new Activity("X", 3),
  new Activity("A", 5, ["X"]),
  new Activity("B", 3, ["X"]),
  new Activity("C", 7, ["B", "A"]),
];

const testActivities3 = [
  new Activity("A", 6),
  new Activity("B", 5),
  new Activity("C", 10, ["A"]),
  new Activity("D", 3, ["A", "B"]),
  new Activity("E", 7, ["D"]),
  new Activity("F", 3, ["C", "E"]),
  new Activity("G", 4, ["C", "E"]),
  new Activity("H", 5, ["C", "E"]),
  new Activity("I", 6, ["F"]),
  new Activity("J", 3, ["H"]),
  new Activity("K", 2, ["I", "G", "J"]),
];

const testResults1 = [
  {
    id: "A",
    duration: 3,
    predecessor: [],
    es: 0,
    ef: 3,
    ls: 0,
    lf: 3,
    successor: ["C", "D"],
    tf: 0,
    ff: 0,
    critical: true,
  },
  {
    id: "B",
    duration: 3,
    predecessor: [],
    es: 0,
    ef: 3,
    ls: 0,
    lf: 3,
    successor: ["C", "D"],
    tf: 0,
    ff: 0,
    critical: true,
  },
  {
    id: "C",
    duration: 3,
    predecessor: ["A", "B"],
    es: 3,
    ef: 6,
    ls: 3,
    lf: 6,
    successor: ["F", "E"],
    tf: 0,
    ff: 0,
    critical: true,
  },
  {
    id: "D",
    duration: 4,
    predecessor: ["A", "B"],
    es: 3,
    ef: 7,
    ls: 6,
    lf: 10,
    successor: ["G"],
    tf: 3,
    ff: 2,
    critical: false,
  },
  {
    id: "E",
    duration: 3,
    predecessor: ["C"],
    es: 6,
    ef: 9,
    ls: 7,
    lf: 10,
    successor: ["G"],
    tf: 1,
    ff: 0,
    critical: false,
  },
  {
    id: "G",
    duration: 2,
    predecessor: ["D", "E"],
    es: 9,
    ef: 11,
    ls: 10,
    lf: 12,
    successor: ["H"],
    tf: 1,
    ff: 1,
    critical: false,
  },
  {
    id: "F",
    duration: 6,
    predecessor: ["C"],
    es: 6,
    ef: 12,
    ls: 6,
    lf: 12,
    successor: ["H"],
    tf: 0,
    ff: 0,
    critical: true,
  },
  {
    id: "H",
    duration: 5,
    predecessor: ["F", "G"],
    es: 12,
    ef: 17,
    ls: 12,
    lf: 17,
    successor: [],
    tf: 0,
    ff: 0,
    critical: true,
  },
];

const testResults2 = [
  {
    id: "X",
    duration: 3,
    predecessor: [],
    es: 0,
    ef: 3,
    ls: 0,
    lf: 3,
    successor: ["B", "A"],
    tf: 0,
    ff: 0,
    critical: true,
  },
  {
    id: "B",
    duration: 3,
    predecessor: ["X"],
    es: 3,
    ef: 6,
    ls: 5,
    lf: 8,
    successor: ["C"],
    tf: 2,
    ff: 2,
    critical: false,
  },
  {
    id: "A",
    duration: 5,
    predecessor: ["X"],
    es: 3,
    ef: 8,
    ls: 3,
    lf: 8,
    successor: ["C"],
    tf: 0,
    ff: 0,
    critical: true,
  },
  {
    id: "C",
    duration: 7,
    predecessor: ["B", "A"],
    es: 8,
    ef: 15,
    ls: 8,
    lf: 15,
    successor: [],
    tf: 0,
    ff: 0,
    critical: true,
  },
];

const testResults3 = [
  {
    id: "B",
    duration: 5,
    predecessor: [],
    es: 0,
    ef: 5,
    ls: 1,
    lf: 6,
    successor: ["D"],
    tf: 1,
    ff: 1,
    critical: false,
  },
  {
    id: "A",
    duration: 6,
    predecessor: [],
    es: 0,
    ef: 6,
    ls: 0,
    lf: 6,
    successor: ["C", "D"],
    tf: 0,
    ff: 0,
    critical: true,
  },
  {
    id: "D",
    duration: 3,
    predecessor: ["A", "B"],
    es: 6,
    ef: 9,
    ls: 6,
    lf: 9,
    successor: ["E"],
    tf: 0,
    ff: 0,
    critical: true,
  },
  {
    id: "C",
    duration: 10,
    predecessor: ["A"],
    es: 6,
    ef: 16,
    ls: 6,
    lf: 16,
    successor: ["F", "G", "H"],
    tf: 0,
    ff: 0,
    critical: true,
  },
  {
    id: "E",
    duration: 7,
    predecessor: ["D"],
    es: 9,
    ef: 16,
    ls: 9,
    lf: 16,
    successor: ["F", "G", "H"],
    tf: 0,
    ff: 0,
    critical: true,
  },
  {
    id: "F",
    duration: 3,
    predecessor: ["C", "E"],
    es: 16,
    ef: 19,
    ls: 16,
    lf: 19,
    successor: ["I"],
    tf: 0,
    ff: 0,
    critical: true,
  },
  {
    id: "H",
    duration: 5,
    predecessor: ["C", "E"],
    es: 16,
    ef: 21,
    ls: 17,
    lf: 22,
    successor: ["J"],
    tf: 1,
    ff: 0,
    critical: false,
  },
  {
    id: "G",
    duration: 4,
    predecessor: ["C", "E"],
    es: 16,
    ef: 20,
    ls: 21,
    lf: 25,
    successor: ["K"],
    tf: 5,
    ff: 5,
    critical: false,
  },
  {
    id: "J",
    duration: 3,
    predecessor: ["H"],
    es: 21,
    ef: 24,
    ls: 22,
    lf: 25,
    successor: ["K"],
    tf: 1,
    ff: 1,
    critical: false,
  },
  {
    id: "I",
    duration: 6,
    predecessor: ["F"],
    es: 19,
    ef: 25,
    ls: 19,
    lf: 25,
    successor: ["K"],
    tf: 0,
    ff: 0,
    critical: true,
  },
  {
    id: "K",
    duration: 2,
    predecessor: ["I", "G", "J"],
    es: 25,
    ef: 27,
    ls: 25,
    lf: 27,
    successor: [],
    tf: 0,
    ff: 0,
    critical: true,
  },
];

module.exports = {
  testResults1,
  testResults2,
  testResults3,
  testActivities1,
  testActivities2,
  testActivities3,
};
